from .car_locator import CarLocator
from .car_locator_trt import CarLocatorTRT
from .char_recognizer import CharRecognizer
from .plate_detector import PlateDetector
from .segmentator import Segmentator
from .plate_detector_trt import PlateDetectorTRT
from .segmentator_trt import SegmentatorTRT
from .char_recognizer_trt import CharRecognizerTRT
from .lpr import LPR