properties:
  num_votes: 8
  new_car_time_patient: 5.0
  new_car_iou_threshold: 0.35
# trigger_zone is a list of tuple of [x, y] points in anti-clockwise direction
# fps_simulation should be False if it's streaming ip
cameras:
  camera1:
    type: 'entrance'
    ip: './assets/videos/entrance_1.mp4'
    fps_simulation: 30
    accum_time: 0.5
    trigger_zone:
      - !!python/tuple [531, 983]
      - !!python/tuple [1050, 700]
      - !!python/tuple [565, 565]
      - !!python/tuple [360, 750]
  camera2:
    type: 'entrance'
    ip: './assets/videos/entrance_2.mp4'
    accum_time: 0.5
    fps_simulation: 30
    trigger_zone:
      - !!python/tuple [531, 983]
      - !!python/tuple [1050, 700]
      - !!python/tuple [565, 565]
      - !!python/tuple [360, 750]
  camera3:
    type: 'entrance'
    ip: './assets/videos/entrance_3.mp4'
    fps_simulation: 30
    accum_time: 0.5
    trigger_zone:
      - !!python/tuple [531, 983]
      - !!python/tuple [1050, 700]
      - !!python/tuple [565, 565]
      - !!python/tuple [360, 750]
